# Generated by Django 4.2.4 on 2023-08-16 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mitter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='followers',
            new_name='follows',
        ),
    ]
