# Generated by Django 4.2.4 on 2023-08-17 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitter', '0004_meep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meep',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
