# Generated by Django 4.2.4 on 2023-08-19 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitter', '0005_alter_meep_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
