# Generated by Django 4.2.4 on 2023-08-19 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitter', '0008_profile_facebook_link_profile_github_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='homepage_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
