# Generated by Django 4.2.4 on 2023-08-19 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mitter', '0009_alter_profile_homepage_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='linkedid_link',
            new_name='linkedin_link',
        ),
    ]
